kind: kind: Service
apiVersion: v1
metadata:
  name:  myservice
  label:
     app: myspringbootapp
spec:
  selector:
    app: myspringbootapp     
  type:  Loadbalancer
  ports: 
  -  nodeport: 30036
     port:  80
     targetPort:  9099